site_name: brikWork Docs
site_url: https://brikwork.readthedocs.io/en/latest/

markdown_extensions:
  - smarty
  - extra
  - toc
  - nl2br
  - admonition

nav:
  - ./index.md
  - ./Example.md
  - ./Syntax.md
  - ./Using.md
  - 'Reference':
    - ./Properties.md
    - ./Values.md
    - ./Briks.md
    - ./Templates.md
  - ./Glossary.md
  - ./changelog.md
  - 'Home Page': 'https://codlark.itch.io/brikwork'

theme:
  name: readthedocs
  highlightjs: false